package pl.sudnev.orderflow.order;

public enum OrderEventType {
  ORDER_CREATED_EVENT,
  PRODUCT_ADDED_EVENT,
  PRODUCT_REMOVED_EVENT,
  ORDER_CANCELLED_EVENT,
  ORDER_ISSUED_EVENT,
  PAYMENT_RECEIVED_EVENT
}
